kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
    app.openshift.io/connects-to: >-
      [{"apiVersion":"apps/v1","kind":"Deployment","name":"selenium-hub"}]
    app.openshift.io/route-disabled: 'false'
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"node-chrome:110","namespace":"selenium-test"},"fieldPath":"spec.template.spec.containers[?(@.name==\"node-chrome\")].image","pause":"false"}]
    openshift.io/generated-by: OpenShiftWebConsole
  name: node-chrome-110
  namespace: selenium-test
  labels:
    app: node-chrome-110
    app.kubernetes.io/component: node-chrome-110
    app.kubernetes.io/instance: node-chrome-110
    app.kubernetes.io/name: node-chrome-110
    app.kubernetes.io/part-of: selenium-grid
    app.openshift.io/runtime-namespace: selenium-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-chrome-110
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: node-chrome-110
        deployment: node-chrome-110
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
    spec:
      containers:
        - name: node-chrome-110
          image: >-
            image-registry.openshift-image-registry.svc:5000/selenium-test/node-chrome:110
          ports:
            - containerPort: 7900
              protocol: TCP
            - containerPort: 5900
              protocol: TCP
            - containerPort: 5555
              protocol: TCP
          env:
            - name: SE_EVENT_BUS_HOST
              value: selenium-hub.selenium-test.svc.cluster.local
            - name: SE_EVENT_BUS_PUBLISH_PORT
              value: '4442'
            - name: SE_EVENT_BUS_SUBSCRIBE_PORT
              value: '4443'
            - name: SE_NODE_PORT
              value: '5555'
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600