apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: webtest-chrome
  namespace: demo-selenium
spec:
  params:
    - name: test_url
      type: string
    - name: test_keyword
      type: string
    - name: selenium_hub_host
      type: string
  steps:
    - name: website-load-test
      env:
        - name: SELENIUM_HUB_URL
          value: $(inputs.params.selenium_hub_host)
        - name: TEST_URL
          value: $(inputs.params.test_url)
        - name: TEST_KEYWORD
          value: $(inputs.params.test_keyword)
      image: >-
        image-registry.openshift-image-registry.svc:5000/demo-selenium/python-selenium:latest
      script: |
        echo Task begins - Execute Selenium Hub workloads
        echo 
        echo Wait for application to finish spooling up
        sleep 30
        echo  
        echo Begin Web Test

        python3 -c "

        import sys,os
        from selenium import webdriver
        from selenium.webdriver.common.keys import Keys
        from selenium.webdriver.support.wait import WebDriverWait
        from time import sleep

        hub_url = os.environ.get('SELENIUM_HUB_URL')
        chrome_versions = ['110.0', '119.0', '121.0']

        for version in chrome_versions:
            print('Testing Chrome version ' + version + ' with URL: ' + os.environ.get('TEST_URL'))
            options = webdriver.ChromeOptions()
            options.set_capability(name='browserVersion', value=version)
            options.accept_insecure_certs = True
            driver = webdriver.Remote(command_executor=hub_url, options=options)
            driver.get(os.environ.get('TEST_URL'))
            WebDriverWait(driver, 10).until(lambda d: os.environ.get('TEST_KEYWORD') in d.page_source)
            page_content = driver.page_source
            sleep(15)
            driver.quit()
            if os.environ.get('TEST_KEYWORD') not in page_content:
              print('Testing Chrome version ' + version + ' failed. Keyword ' + os.environ.get('TEST_KEYWORD') + ' not found')
              sys.exit(1)
            else:
              print('Testing Chrome version ' + version + ' successful')
        print('Website load test successful with all browsers versions')

        "

        echo 
        echo Task finished
